# Generated by Django 3.0.3 on 2020-02-25 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_todo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='created',
            new_name='created_at',
        ),
    ]
